dynamics_engine:
  engine: lammps
  gamma_threshold: 2.0
  mock: true
  n_steps: 100
  parameters:
    dynamics_halt_probability: 0.5
logging:
  level: INFO
oracle:
  dft:
    code: quantum_espresso
    command: mpirun -np 4 pw.x
    max_retries: 1
    pseudopotentials:
      Fe: tutorial_data/Fe.pbe.UPF
      Mg: tutorial_data/Mg.pbe.UPF
      O: tutorial_data/O.pbe.UPF
      Pt: tutorial_data/Pt.pbe.UPF
  mock: true
orchestrator:
  dataset_file: dataset.pckl.gzip
  max_cycles: 2
  validation_split: 0.25
project:
  name: TutorialProject
  root_dir: /app/tutorial_data
structure_generator:
  initial_exploration: random
  strategy: adaptive
trainer:
  max_epochs: 1
  mock: true
  potential_type: pace
validator:
  elastic_strain: 0.01
  eos_strain: 0.1
  phonon_supercell:
  - 2
  - 2
  - 2
  test_set_ratio: 0.1
version: 0.1.0
